version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam build --template-file skill-lambda/template.yaml
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name amber-skill-stack --resolve-s3 --capabilities CAPABILITY_IAM