AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Amber Alexa Skill

  Pull live pricing data from Amber for Alexa
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        AMBER_API_ENDPOINT: https://api.amberelectric.com.au/prices/listprices
        POST_CODE: 3204

Resources:
  AmberFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: amber/
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
          AmberLookup:
            Type: AlexaSkill
            Properties:
              SkillId: amzn1.ask.skill.e6742fb8-dc52-4c9c-b903-8b786354a9d8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AmberFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AmberFunction.Arn
  AmberFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AmberFunctionRole.Arn
